version: "3.7"
services:
  postgres:
    image: postgres:11.5
    container_name: test_task_database
    networks:
      - test_task
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "test"

networks:
  test_task:
